### PR TITLE
Fix compiler warnings

### PR DESCRIPTION
**Pull request by beerriot**
Building concord-bft generated a number of warnings around:

 * extra semicolons
 * signed/unsigned comparison
 * unused functions/variables
 * unmatched enumeration values in switch statements

This change cleans them all up, so that no warnings are reported with either Clang 3.8.0 or GNU 5.4.0.

Since the changes were fairly extensive to CommFactory.{cpp,hpp}, I also cleaned up the cpplint complaints for those files (the last three commits here).

I also accidentally committed my addition to .gitignore for emacs temporary files. Sorry to include it in unrelated changes, but it's a good and simple addition.

### CODE REVIEW

**Comment by guyg8** [comment]
@beerriot: 
Overall it looks good. Thanks!
Comments/Questions:
The new functions in CommFactory.cpp (create_config_impl) should be part of the bftEngine namespace (at least according to CommFactory.hpp).
Why the template function “create_config(Args... args)” was moved to CommFactory.cpp ? did you check that the instances of this template function are actually created (and the linker is able to find them …)?

**Comment by guyg8** [comment]
@salieri11:
Do we really need all the “template games” in CommFactory.cpp/hpp ? ( This code may be more readable without templates)

**Comment by salieri11** [comment]
@guy I think I got rid of them in the integration commits

**Comment by guyg7** [comment]
@salieri11:
Great. Let's try to keep the interfaces as simple as possible.
I suggest to also delete these functions from this repository.

**Comment by beerriot** [comment]
re: config-impl functions -- I didn't do much checking here, because the functions are not used anywhere. As it seems @guyg7 and @salieri11 agree, I will remove them and push an update here. Thanks for reviewing!

**Pull request merged**
