### PR TITLE
ConcordClient Interface

### PR DESCRIPTION
**Pull request by robem**
This change introduces the Concord Client C++ interface.
See commits for details.

### CODE REVIEW

**Review by shgandhi — APPROVED** [review]
Thanks for the change @robem! LGTM!

**Review by Liorgal28 — APPROVED** [review]
Looks good @robem!

**Review by andrewjstone — APPROVED** [review]
Looks great @robem. This is a huge step forward for the product.

One suggestion: I feel that the concord-client api subscription mechanism should be agnostic to implementation. Currently it's coupled to thin replica, but only by types. We may want to move those types into a separate library to enable decoupling.

**Comment by robem** [comment]
> Looks great @robem. This is a huge step forward for the product.
> 
> One suggestion: I feel that the concord-client api subscription mechanism should be agnostic to implementation. Currently it's coupled to thin replica, but only by types. We may want to move those types into a separate library to enable decoupling.

We are doing the same for the BFT client. However, you can argue that the BFT client **is** Concord Client and maybe the thin replica functionality will become part of it.
Are you suggesting we should copy `TrsConnectionConfig`, to e.g. `SubscriptionConfig`, and combine it with the client id?

**Comment by andrewjstone** [comment]
> > Looks great @robem. This is a huge step forward for the product.
> > One suggestion: I feel that the concord-client api subscription mechanism should be agnostic to implementation. Currently it's coupled to thin replica, but only by types. We may want to move those types into a separate library to enable decoupling.
> 
> We are doing the same for the BFT client. However, you can argue that the BFT client **is** Concord Client and maybe the thin replica functionality will become part of it.
> Are you suggesting we should copy `TrsConnectionConfig`, to e.g. `SubscriptionConfig`, and combine it with the client id?

Yep. That's basically what I'm suggesting. It's certainly not necessary in this commit though. It's just something to think about.

**Review by andrewjstone — APPROVED** [review]
Looks great! Ship it!

**Pull request merged**
