### PR TITLE
Fix for concurrent access to AsyncTimeRecorderMap in PreProcessor.

### PR DESCRIPTION
**Pull request by HristoStaykov**
We no longer use a map to store the measurements. Instead we directly
move them in the AsyncPreProcessJob, and rely on the lifetime of this
job to finalize the measurement. Since we have a 1:1 mapping of Client
Requests to AsyncPreProcessJob-s and we delete the jobs after we execute
them this has to be equivalent.

### CODE REVIEW

**Review by yuliasherman — APPROVED** [review]
LGTM

**Review by yontyon — APPROVED** [review]
LGTM

**Review by andrewjstone — APPROVED** [review]
LGTM. Thanks for the fix @HristoStaykov

**Comment by KTeofanidis** [comment]
LGTM

**Pull request merged**
