### PR TITLE
[Apollo] Checkpoint propagation after primary isolation

### PR DESCRIPTION
**Pull request by shgandhi**
In this test, the goal is to verify checkpoint creation and propagation workflow when an adversary intercepts and drops all outgoing packets from the current primary.

### CODE REVIEW

**Comment by teoparvanov** [comment]
PS: @shgandhi could you please re-trigger CI with a small commit, as it seems to be stuck? Thanks!

**Comment by shgandhi** [comment]
Thanks for the review @teoparvanov. Re-triggered the CI with a small change.

**Comment by teoparvanov** [comment]
Hi Shruti, I just merged your other test, so this PR needs to be rebased before we can merge it too.

**Comment by shgandhi** [comment]
Hi Teo, this PR has been rebased.

**Pull request merged**
