### PR TITLE
Arrangement of the readme badges

### PR DESCRIPTION
**Pull request by KTeofanidis**
Change the arrangement of the readme badges. Change the workflow names to be more friendly.

### CODE REVIEW

**Comment by teoparvanov** [comment]
@KTeofanidis could you please attach a screenshot of the end result? It's kind of hard to imagine just from the code 😄 
Thanks!

**Comment by KTeofanidis** [comment]
You can see how it looks in my fork https://github.com/KTeofanidis/concord-bft/tree/format_readme_badges

**Review by teoparvanov — APPROVED** [review]
LGTM, thanks!

**Review by f-squirrel — APPROVED** [review]
Looks great, thank you @KTeofanidis !

**Pull request merged**
