### PR TITLE
Upgrading rocksdb version

### PR DESCRIPTION
**Pull request by yontyon**
Upgrade rocksdb version to v6.8.1

### CODE REVIEW

**Comment by yontyon** [comment]
@teoparvanov I had to clear the caches due to building issues.
Once I did it, all tests passed smoothly.

**Comment by teoparvanov** [comment]
> 
> 
> @teoparvanov I had to clear the caches due to building issues.
> Once I did it, all tests passed smoothly.

Hi Yoni, thanks for the clarification! If you don't mind, I'll just rerun the full CI job, to make sure this change does not introduce intermittent failures. After that, I'll be pretty confident about merging the change into master.

**Comment by teoparvanov** [comment]
As discussed above, I've rerun twice all CI jobs related to this PR. It seems stable enough, so we can go ahead and merge into master.

**Comment by andrewjstone** [comment]
I merged it into master, but got timeouts on 3 out of 8 jobs. See https://github.com/vmware/concord-bft/runs/700141815

They all timeout in different tests. The only related thing I see is that they are all release builds.

**Comment by andrewjstone** [comment]
> I merged it into master, but got timeouts on 3 out of 8 jobs. See https://github.com/vmware/concord-bft/runs/700141815
> 
> They all timeout in different tests. The only related thing I see is that they are all release builds.
> 
> I restarted one of the jobs to see what happens. My hope is that this is unrelated to RocksDB

Re-run of the job worked fine, and compilation in product worked as well.

**Comment by teoparvanov** [comment]
Hey Andrew, I think I have an explanation...

https://github.com/vmware/concord-bft/pull/615

**Comment by andrewjstone** [comment]
> Hey Andrew, I think I have an explanation...
> 
> #615

Makes sense. Our graceful shutdown probably is not very graceful in all cases.

**Pull request merged**
