### PR TITLE
Implement new PreProcessBatchRequestMsg

### PR DESCRIPTION
**Pull request by yuliasherman**
+ Add configuration parameter
+ Add spanContextSize to PreProcessRequestMsg header

### CODE REVIEW

**Review by teoparvanov — COMMENTED** [review]
Hi Yulia, the PR description seems incomplete, but maybe it's me?
Also, is it worth adding a unit test for the new `PreProcessBatchRequestMsg` ?

Thanks!
-- Teo

**Review by teoparvanov — APPROVED** [review]
LGTM!

**Comment by yuliasherman** [comment]
> Hi Yulia, the PR description seems incomplete, but maybe it's me?
> Also, is it worth adding a unit test for the new `PreProcessBatchRequestMsg` ?
> 
> Thanks!
> -- Teo

Sure, it's in process.

**Review by Liorgal28 — APPROVED** [review]
LGTM

**Pull request merged**
