### PR TITLE
[WIP] GitHub actions experimenting

### PR DESCRIPTION
**Pull request by tdimitrov**
This is for testing purposes only, please don't merge.

### CODE REVIEW

**Comment by tdimitrov** [comment]
Thanks @andrewjstone 
I think we can't see any action here until the workflow is committed. However here is a run from m fork: https://github.com/tdimitrov/concord-bft/actions/runs/110535377

**Comment by andrewjstone** [comment]
> Thanks @andrewjstone
> I think we can't see any action here until the workflow is committed. However here is a run from m fork: https://github.com/tdimitrov/concord-bft/actions/runs/110535377

Cool. Unfortunately it looks like each job took about twice as long. I wonder if that's related to the underlying hardware perf. The good news is the overall CI run only took about 20% longer since all jobs were able to run in parallel.

**Comment by tdimitrov** [comment]
Are you comparing the overall running times? I noticed that the built I've sent has a cache miss so it includes provisioning. At quick glance build and test times look similar.
I'll try to run another build which will use the cache and compare the results.

**Comment by andrewjstone** [comment]
> Are you comparing the overall running times? I noticed that the built I've sent has a cache miss so it includes provisioning. At quick glance build and test times look similar.
> I'll try to run another build which will use the cache and compare the results.

Yes the overall running times. Thanks!

**Pull request closed without merging**
