### PR TITLE
Synchronize msg processing thread with recovery

### PR DESCRIPTION
**Pull request by cloudnoize**
The main thread should handle recovery before msg processing thread starts accepting msgs.
When the main thread finishes handling recovery in the replica implementation, it notifies the msg processing thread to start accepting msgs.

### CODE REVIEW

**Comment by cloudnoize** [comment]
> As far as I understand the idea is to process the recovered messages before processing the new ones.
> If so, can we just not call [msgsCommunicator_->startMsgsProcessing(config_.replicaId)](https://github.com/vmware/concord-bft/blob/master/bftengine/src/bftengine/ReplicaBase.cpp#L53) in `ReplicaBase::start` but call it in `ReplicaImp::start`?
> Thus, the dispatcher thread will be launched only when Replica is ready to go.

@f-squirrel  That was the first imp choice but encountered issues like read-only replica needs the same mechanism and a dependency on the order of operations, which I currently don't remember the error I received.

**Comment by f-squirrel** [comment]
@cloudnoize , I am not sure I understand the problem.
`msgsCommunicator_->startMsgsProcessing(config_.replicaId);` is the last operation in `ReplicaBase::start`.
All the "replicas" that inherit from the `ReplicaBase` do `msgsCommunicator_->startMsgsProcessing(config_.replicaId);` in their implementation of `start`(`ReplicaImp`, `ReplicaForStateTransfer`).
The `ReadOnlyReplica` does not need to do it because it calls `ReplicaForStateTransfer::start()`.
This way we do need to use the additional synchronization primitives.

**Comment by cloudnoize** [comment]
@f-squirrel  think I recall. if you extract `msgsCommunicator_->startMsgsProcessing(config_.replicaId);` from base, you need to call it in `start` of each replica inheritance (imp,st,ro) but imp and ro ,need to call start of state-transfer, so where would you put the statement in state-transfer replica?

**Comment by f-squirrel** [comment]
@cloudnoize , you're right, I got lost in the inheritance hierarchy...

As far as I see we actually instantiate only two types of replicas: [`ReplicaImp` and `ReadOnlyReplica`](https://github.com/vmware/concord-bft/blob/master/bftengine/include/bftengine/Replica.hpp#L79). The `ReplicaForStateTransfer` is never instantiated but only used as a base class.
Hence we may to call `startMsgsProcessing` only in the end of `ReplicaImp::start` and `ReadOnlyReplica::start`.
WDYT?

If there are no other implications, I suggest considering the simpler solution i.e. just moving the function call to the upper hierarchy.

**Comment by salieri11** [comment]
Just a general question: doesn't the recovery process use the same message dispatching mechanism?

**Comment by cloudnoize** [comment]
> Just a general question: doesn't the recovery process use the same message dispatching mechanism?

@salieri11 nope, it process committed msgs that it knows that their execution was aborted, on start. must be before any msg processed by the dispatching mechanism.

**Comment by salieri11** [comment]
> > Just a general question: doesn't the recovery process use the same message dispatching mechanism?
> 
> @salieri11 nope, it process committed msgs that it knows that their execution was aborted, on start. must be before any msg processed by the dispatching mechanism.

So who provides the thread for the processing?

**Comment by cloudnoize** [comment]
> > > Just a general question: doesn't the recovery process use the same message dispatching mechanism?
> > 
> > 
> > @salieri11 nope, it process committed msgs that it knows that their execution was aborted, on start. must be before any msg processed by the dispatching mechanism.
> 
> So who provides the thread for the processing?

main thread is responsible for the recovery.
it also calls replica base start, that starts the processing thread

**Pull request merged**
