### PR TITLE
Remove key prefix from TRC and TRS

### PR DESCRIPTION
**Pull request by shgandhi**
This PR contains commits that remove key_prefix from TRC and TRS. The reason this change is required is because TRS only streams events and every event is already prefixed with “F” (F = fragment), hence the client application doesn't need to filter for fragment kv-pairs in the read-service.
Please see individual commits for more detail.

### CODE REVIEW

**Comment by f-squirrel** [comment]
What is the motivation behind removing the key prefix?

**Comment by shgandhi** [comment]
> What is the motivation behind removing the key prefix?

@f-squirrel  this is because TRS now only streams events and every event is already prefixed with “F” (F = fragment), Daml doesn't need to filter for fragment kv-pairs in the read-service.

**Comment by f-squirrel** [comment]
Thank you for the explanation, @shgandhi !

**Review by f-squirrel — APPROVED** [review]

**Comment by shgandhi** [comment]
Thanks for the review @robem, @f-squirrel.
Marking this as WIP to avoid accidental merge, waiting for the corresponding closed-source change to get approved.

**Pull request merged**
